//
//  ApiendPoints.swift
//  MyOrder
//
//  Created by sourabh on 10/10/20.
//


let kSERVERBASEURL                  =   "https://aptechbangalore.com/myorder/api/"

let kManufactureRegister            =   "manufacture_register"
let kStockistRegister               =   "stockist_register"
let kDistributorRegister            =   "distributor_register"
let kRetailerRegister               =   "retailer_register"
let kSalesagentRegister             =   "salesagent_register"
let kManufactureLogin               =   "manufacture_login"
let kStockistLogin                  =   "stockist_login"
let kDistributorLogin               =   "distributor_login"
let kRetailerLogin                  =   "retailer_login"
let kSalesagentLogin                =   "salesagent_login"
let kManufactureForget              =   "manufacture_forget"
let kStockistForget                 =   "stockist_forget"
let kDistributorForget              =   "distributor_forget"
let kRetailerForget                 =   "retailer_forget"
let kSalesagentForget               =   "salesagent_forget"
let kManufactureForgetResend        =   "manufacture_forget_resend"
let kStockistForgetResend           =   "stockist_forget_resend"
let kDistributorForgetResend        =   "distributor_forget_resend"
let kRetailerForgetResend           =   "retailer_forget_resend"
let kSalesagentForgetResend         =   "salesagent_forget_resend"
let kManufactureForgetVerify        =   "manufacture_forget_verify"
let kStockistForgetVerify           =   "stockist_forget_verify"
let kDistributorForgetVerify        =   "distributor_forget_verify"
let kRetailerForgetVerify           =   "retailer_forget_verify"
let kSalesagentForgetVerify         =   "salesagent_forget_verify"
let kManufactureForgetReset         =   "manufacture_forget_reset"
let kStockistForgetReset            =   "stockist_forget_reset"
let kDistributorForgetReset         =   "distributor_forget_reset"
let kRetailerForgetReset            =   "retailer_forget_reset"
let kSalesagentForgetReset          =   "salesagent_forget_reset"
let kDashboardHomeProducts          =   "homeProducts"
let kHomeProduct                    =   "homeProduct"
let kCategory                       =   "category"
let kProduct                        =   "product"
let kProductDetail                  =   "productdetail"
let kGetDependendSize               =   "get_dependend_size"
let kWishListUpdate                 =   "wishlist_add_update"
let kWishlist                       =   "wishlist"
let kFiltersnew                     =   "filtersnew"
let kFilterProduct                  =   "filterProduct"
let kCartList                       =   "cart"
let kCartAddUpdate                  =   "cart_add_update"
let kCartCoupon                     =   "applyCoupon"
let kCartReview                     =   "cart_review"
let kAddAddress                     =   "addAddress"
let kAddressList                    =   "userAddresss"
let kAddDefaultAddress              =   "addDefaultAddress"
let kDeleteAddress                  =   "deleteAddress"
let kUpdateAddress                  =   "updateAddress"
let kSaveOrder                      =   "saveOrder"
let kManufactureProfile             =   "manufacture_profile"
let kStockistProfile                =   "stockist_profile"
let kDistributorProfile             =   "distributor_profile"
let kRetailerProfile                =   "retailer_profile"
let kAgentProfile                   =   "agent_profile"
let kManufactureProfileUpdate       =   "manufacture_profile_update"
let kStockistProfileUpdate          =   "stockist_profile_update"
let kDistributorProfileUpdate       =   "distributor_profile_update"
let kRetailerProfileUpdate          =   "retailer_profile_update"
let kAgentProfileUpdate             =   "agent_profile_update"
let kOrderList                      =   "order_list"
let kOrderInvoiceList               =   "order_invoice_list"
let kOrderInvoicePayment            =   "order_invoice_payment"
let kIssuesList                     =   "issues_list"
let kIssuesAdd                      =   "issues_add"
let kTicketList                     =   "ticket_list"
let kTicketAdd                      =   "ticket_add"
let kLedgerList                     =   "ledger_list"
let kLedger                         =   "ledger"
let kStateList                      =   "state_listing"
let kCityList                       =   "city_listing"
let kAreaList                       =   "area_listing"
let kCoupons                        =   "coupons"
let kCancelReason                   =   "getReason"
let kCancelOrder                    =   "cancel_return_order"
let kLegalPages                     =   "legalPages"
let kDashboard                      =   "dashboard"
let kOrderListDelivered             =   "leveling_order_list"
let kOrderListDispatched            =   "order_list_delivered"
let kReward                         =   "reward"
let kProductSearch                  =   "productsearch"
let kRewardRootCat                  =   "rewardRootCat"
let kRewardProducts                 =   "rewardProducts"
let kRewardOrderList                =   "rewardorder_list"
let kRewardCart                     =   "rewardCart"
let kRewardCartAddUpdate            =   "rewardCart_add_update"
let kRewardCartReview               =   "rewardCart_review"
let kRewardSaveOrder                =   "rewardSaveOrder"
let kRewardPoints                   =   "rewardPoints"
let kLevelingIssuesList             =   "leveling_issues_list"









